config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"
  
  get "about-us", to: "about#index", as: :about

  #registrations routes
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  delete "logout", to: "session#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password  
    validates :email, presence: true, format: {with: /\A(.+)@(.+)\z/, message: "Email invalid"}
end
 

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end        


end    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index 
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
        end   
    end
end   

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end
    def create 
        @user = User.new(user_params) 
        if @user.save 
            session[:user_id] = @user.id
            redirect_to root_path, notice: "account created successfully"
        else
            render :new 
        end
    end 
    def user_params 
        params.require(:user).permit(:email, :password, :password_confirmation)
    end       

end    

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "logged out" 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="d-flex justify-content-center">
    <h1>Contact us to sign-up </h1>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTweet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
    <%= render partial: 'shared/flash' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex justify-content-center align-items-center">
<h1 class="text-primary">Wellcome to home page <h1>
</div>

<% if @user %>
    Logged in as <%= @user.email %>
    <%= button_to "Log Out", logout_path, method: :delete, class:"btn btn-secondary" %>
   
    
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
    <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert]%>
    <div class="alert alert-warning" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'Navbar', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
           <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>